In [1]:
#create model class
import torch
import torch.nn as nn

### Non-Sequential Method

In [2]:
# class Model(nn.Module):

#   def __init__(self, num_features):
#     super().__init__()
#     self.linear1 = nn.Linear(num_features, 3)
#     self.relu = nn.ReLU()
#     self.linear2 = nn.Linear(3, 1)
#     self.sigmoid = nn.Sigmoid()

#   def forward(self, features):
#     out = self.linear1(features)
#     out = self.relu(out)
#     out = self.linear2(out)
#     out = self.sigmoid(out)
#     return out

### Sequential Method

In [3]:
class Model(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.network = nn.Sequential(
      nn.Linear(num_features, 3),
      nn.ReLU(),
      nn.Linear(3, 1),
      nn.Sigmoid(),
    )

  def forward(self, features):
    out = self.network(features)
    return out

In [4]:
# create dataset
torch.manual_seed(1)
features = torch.rand(10, 5)

# create model
model = Model(features.shape[1])

# call model for forward pass
# model.forward(features)             # will work but not prefered by torch
model(features)                       # works due to magic function __call__

tensor([[0.4565],
        [0.4608],
        [0.4681],
        [0.4661],
        [0.4695],
        [0.4651],
        [0.4976],
        [0.4951],
        [0.4596],
        [0.4528]], grad_fn=<SigmoidBackward0>)

In [5]:
# show model weights for Non Sequential
# print(f'Layer 1 weights: {model.linear1.weight}')
# print(f'Layer 2 bias: {model.linear2.bias}')

In [6]:
# show model weights for Sequential
print(f'Layer 1 weights: {model.network[0].weight}')
print(f'Layer 2 bias: {model.network[2].bias}')

Layer 1 weights: Parameter containing:
tensor([[-0.4299, -0.2132,  0.2427, -0.1087,  0.4454],
        [ 0.3585, -0.0209, -0.2985,  0.2723,  0.1388],
        [-0.2891,  0.2905,  0.2715,  0.3966, -0.2507]], requires_grad=True)
Layer 2 bias: Parameter containing:
tensor([-0.1354], requires_grad=True)


In [7]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00