## Import libraries

In [1]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

## Data Import

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [5]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

## train test split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

## scaling

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [8]:
X_train

array([[ 2.06807613,  0.70796254,  2.01808961, ...,  1.58372809,
        -1.34965148, -0.69052678],
       [ 0.58499154,  0.58892831,  0.61849167, ..., -0.16562439,
        -0.27031209, -0.24091177],
       [ 0.59618463, -0.85348643,  0.50490111, ...,  0.29827576,
        -0.96645407, -0.62882544],
       ...,
       [ 0.19603162,  0.19914957,  0.15682719, ..., -0.21051795,
        -0.85628481, -0.96737803],
       [ 0.29397117,  2.6288482 ,  0.45216264, ...,  1.79323138,
         1.88996335,  3.0517939 ],
       [-0.28247303,  0.27617172, -0.33242357, ..., -1.10464807,
        -0.34854823, -0.52205528]], shape=(455, 30))

## label encoding

In [9]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

In [10]:
y_train

array([1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,

## Numpy arrays to PyTorch tensors

In [11]:
X_train_tensor = torch.from_numpy(X_train).float()
X_test_tensor = torch.from_numpy(X_test).float()

y_train_tensor = torch.from_numpy(y_train).float().view(-1, 1)
y_test_tensor = torch.from_numpy(y_test).float().view(-1, 1)

In [12]:
X_train_tensor.shape

torch.Size([455, 30])

In [13]:
X_train_tensor

tensor([[ 2.0681,  0.7080,  2.0181,  ...,  1.5837, -1.3497, -0.6905],
        [ 0.5850,  0.5889,  0.6185,  ..., -0.1656, -0.2703, -0.2409],
        [ 0.5962, -0.8535,  0.5049,  ...,  0.2983, -0.9665, -0.6288],
        ...,
        [ 0.1960,  0.1991,  0.1568,  ..., -0.2105, -0.8563, -0.9674],
        [ 0.2940,  2.6288,  0.4522,  ...,  1.7932,  1.8900,  3.0518],
        [-0.2825,  0.2762, -0.3324,  ..., -1.1046, -0.3485, -0.5221]])

In [14]:
y_train_tensor.shape

torch.Size([455, 1])

## Defining Model

In [15]:
class MySimpleNN(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, X):
    out = self.linear(X)
    out = self.sigmoid(out)
    return out
  
  # def loss_function(self, y_pred, y):
  #   # Clamp predictions to avoid log(0)
  #   epsilon = 1e-7
  #   y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

  #   # Calculate loss
  #   loss = -((y * torch.log(y_pred)) + ((1-y) * torch.log(1-y_pred))).mean()
  #   return loss   

### Important Parameters

In [16]:
learning_rate = 0.1
epochs = 25

In [17]:
# define loss function
loss_function = nn.BCELoss()

## Training Pipeline

In [18]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# print(f'weights shape: {model.weights.shape}')
# print(f'bias shape: {model.bias.shape}')

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)
  # print(f'y_pred: {y_pred}')

  # loss calculate
  # loss = model.loss_function(y_pred, y_train_tensor)              # based on model interior loss func
  loss = loss_function(y_pred, y_train_tensor)

  # zero gradients
  # model.linear.weight.grad.zero_()
  # model.linear.bias.grad.zero_()
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameters update
  # with torch.no_grad():
  #   model.linear.weight -= learning_rate * model.linear.weight.grad
  #   model.linear.bias -= learning_rate * model.linear.bias.grad
  optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.6547492146492004
Epoch: 2, Loss: 0.49442166090011597
Epoch: 3, Loss: 0.41178247332572937
Epoch: 4, Loss: 0.3617997467517853
Epoch: 5, Loss: 0.32758453488349915
Epoch: 6, Loss: 0.3023008108139038
Epoch: 7, Loss: 0.2826434373855591
Epoch: 8, Loss: 0.2667960226535797
Epoch: 9, Loss: 0.25366783142089844
Epoch: 10, Loss: 0.24255958199501038
Epoch: 11, Loss: 0.2330000102519989
Epoch: 12, Loss: 0.22465865314006805
Epoch: 13, Loss: 0.21729625761508942
Epoch: 14, Loss: 0.21073468029499054
Epoch: 15, Loss: 0.20483826100826263
Epoch: 16, Loss: 0.19950170814990997
Epoch: 17, Loss: 0.19464167952537537
Epoch: 18, Loss: 0.19019147753715515
Epoch: 19, Loss: 0.18609677255153656
Epoch: 20, Loss: 0.18231286108493805
Epoch: 21, Loss: 0.17880262434482574
Epoch: 22, Loss: 0.17553485929965973
Epoch: 23, Loss: 0.17248320579528809
Epoch: 24, Loss: 0.16962507367134094
Epoch: 25, Loss: 0.16694115102291107


## Evaluation

In [19]:
# model evaluation
with torch.no_grad():
  y_pred_test = model.forward(X_test_tensor)
  y_pred_test = (y_pred_test > 0.8).float()
  accuracy = (y_test_tensor == y_pred_test).float().mean()
  print(f'Accuracy: {accuracy}')

Accuracy: 0.9385964870452881
