## Import libraries

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

## Data Import

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [5]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

## train test split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

## scaling

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [8]:
X_train

array([[-0.99389683, -0.06739935, -0.92329111, ..., -0.49102672,
         0.10287107, -0.42136714],
       [-0.30879342, -0.75126761, -0.33699351, ..., -0.08353644,
         0.82208837,  0.71929834],
       [ 1.84563814,  0.53011011,  1.89482906, ...,  2.43659137,
         4.38221402,  1.09399867],
       ...,
       [ 1.57159678,  0.99458035,  1.60717945, ...,  0.70235977,
         0.07017937, -0.40594503],
       [-0.72860147,  1.09494327, -0.7016317 , ..., -0.22385295,
        -1.25056513,  0.23264487],
       [-0.49829011, -0.77927586, -0.51931261, ..., -0.9723108 ,
        -0.64576876, -1.15306093]], shape=(455, 30))

## label encoding

In [9]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

In [10]:
y_train

array([0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,

## Numpy arrays to PyTorch tensors

In [11]:
X_train_tensor = torch.from_numpy(X_train).float()
X_test_tensor = torch.from_numpy(X_test).float()

y_train_tensor = torch.from_numpy(y_train).float().view(-1, 1)
y_test_tensor = torch.from_numpy(y_test).float().view(-1, 1)

In [12]:
X_train_tensor.shape

torch.Size([455, 30])

In [13]:
X_train_tensor

tensor([[-0.9939, -0.0674, -0.9233,  ..., -0.4910,  0.1029, -0.4214],
        [-0.3088, -0.7513, -0.3370,  ..., -0.0835,  0.8221,  0.7193],
        [ 1.8456,  0.5301,  1.8948,  ...,  2.4366,  4.3822,  1.0940],
        ...,
        [ 1.5716,  0.9946,  1.6072,  ...,  0.7024,  0.0702, -0.4059],
        [-0.7286,  1.0949, -0.7016,  ..., -0.2239, -1.2506,  0.2326],
        [-0.4983, -0.7793, -0.5193,  ..., -0.9723, -0.6458, -1.1531]])

In [14]:
y_train_tensor.shape

torch.Size([455, 1])

In [15]:
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):

  def __init__(self, features, labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return len(self.features)
  
  def __getitem__(self, idx):
    return self.features[idx], self.labels[idx]

In [16]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [17]:
train_dataset[10]

(tensor([ 0.3705,  0.7402,  0.3305,  0.2008, -0.3569,  0.0666, -0.3985, -0.3730,
         -0.2564,  0.0971, -0.7121, -1.2890, -0.7483, -0.4656, -1.2983, -0.6168,
         -0.4907, -0.9488, -1.0335, -0.4675,  0.3760,  0.3994,  0.2518,  0.2230,
         -0.0484,  0.5345,  0.5017,  0.1795,  0.4870,  0.8267]),
 tensor([1.]))

In [18]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

## Defining Model

In [19]:
import torch.nn as nn


class MySimpleNN(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, X):
    out = self.linear(X)
    out = self.sigmoid(out)
    return out  

### Important Parameters

In [20]:
learning_rate = 0.1
epochs = 25

In [21]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loss function
loss_function = nn.BCELoss()

## Training Pipeline

In [22]:
# define loop
for epoch in range(epochs):

  for batch_features, batch_labels in train_loader:

    # forward pass
    y_pred = model(batch_features)
    # print(f'y_pred: {y_pred}')

    # loss calculate
    loss = loss_function(y_pred, batch_labels)

    # zero gradients
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    # parameters update
    optimizer.step()

    # print loss in each epoch
    print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.8610634207725525
Epoch: 1, Loss: 0.6191916465759277
Epoch: 1, Loss: 0.4427398145198822
Epoch: 1, Loss: 0.38690441846847534
Epoch: 1, Loss: 0.3738236427307129
Epoch: 1, Loss: 0.32234859466552734
Epoch: 1, Loss: 0.31650304794311523
Epoch: 1, Loss: 0.2955951690673828
Epoch: 1, Loss: 0.24227364361286163
Epoch: 1, Loss: 0.24349743127822876
Epoch: 1, Loss: 0.2598179876804352
Epoch: 1, Loss: 0.21386075019836426
Epoch: 1, Loss: 0.21435977518558502
Epoch: 1, Loss: 0.1871834099292755
Epoch: 1, Loss: 0.18524621427059174
Epoch: 2, Loss: 0.19390934705734253
Epoch: 2, Loss: 0.18632465600967407
Epoch: 2, Loss: 0.18944716453552246
Epoch: 2, Loss: 0.19397005438804626
Epoch: 2, Loss: 0.1369907557964325
Epoch: 2, Loss: 0.23826700448989868
Epoch: 2, Loss: 0.20718532800674438
Epoch: 2, Loss: 0.2366051971912384
Epoch: 2, Loss: 0.1710040420293808
Epoch: 2, Loss: 0.1471714973449707
Epoch: 2, Loss: 0.19289347529411316
Epoch: 2, Loss: 0.1772894561290741
Epoch: 2, Loss: 0.11672563850879669
Epoc

## Evaluation

In [23]:
# model evaluation using test_loader
model.eval()        # Set the model to eval mode
accuracy_list = []

with torch.no_grad():
  for batch_features, batch_labels in test_loader:
    # forward pass
    y_pred_test = model.forward(batch_features)
    y_pred_test = (y_pred_test > 0.8).float()

    # Calculate accuracy for the current batch
    batch_accuracy = (batch_labels== y_pred_test).float().mean().item()
    accuracy_list.append(batch_accuracy)

# Calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy}')

Accuracy: 0.9296875
